---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: "192.168.33.33" }]

provisioner:
  name: salt_solo
  formula: influxdb
  pillars-from-files:
    influxdb.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - influxdb
  state_top:
    base:
      "*":
        - influxdb
        - influxdb.cli

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
